### ISSUE TITLE
Some problems in codings

### ISSUE THREAD

**Issue by chouqin3** [iamaaditya/image-compression-cnn#10]
In combine_images.py, 143 lines, if current_size<= original_size*(1 + args.threshold_pct/100.0). It means current_size is **large** than standard JPEG, because threshold_pct is set 20 by default at begaining. But in papers, you said your algorithm achieves higher visual quality for **the same** compressed size. How do I understand it?

**Comment by iamaaditya** [comment]
For the paper, we used the threshold of 1 (i.e 1%). 20 in the code might have just been left over from some experiments. Change that value to 1, and you should get similar results as reported in the paper.

**Comment by iamaaditya** [comment]
Please see the README
https://github.com/iamaaditya/image-compression-cnn/blob/67855c9a58aeb784ba0e75347d518aadf9c9ff6e/README.md#compressing-image-using-the-map
