### ISSUE TITLE
the Output image size?

### ISSUE THREAD

**Issue by tuqiangwang** [iamaaditya/image-compression-cnn#13]
Original image and heatmap  are inconsistent in size
why???

**Comment by iamaaditya** [comment]
Heatmap size is dictated by the network. As this network is not
fully-convolutional it outputs a fixed size heatmaps. Heatmap can be
resized to original image.

Thanks and Regards
Adi

**Comment by tuqiangwang** [comment]
How to adjust it? Do you adjust during training or during testing

**Comment by iamaaditya** [comment]
You do not have to adjust it. Just resize the heatmap to the size of the
image.

Thanks and Regards
Adi

**Comment by tuqiangwang** [comment]
But after this adjustment, the content of the heat map and the content of the original map is not a corresponding one. In other words, there is no corresponding heat map output in the original picture

**Comment by iamaaditya** [comment]
Then probably your image is too large and with different aspect ratio. Can
you crop your image to the correct aspect ratio, so that after resizing all
the objects are in the same region?


Thanks and Regards
Adi

**Comment by tuqiangwang** [comment]
Thanks 
What is the aspect ratio that your project supports? As an aside, I don't think deep learning does a good job of compressing images. It's not nearly as good as Jpeg, like Google. What do you think?

**Comment by iamaaditya** [comment]
I am not sure but I think it supports square image (1:1). What do you mean
it is not better than JPEG. This project uses JPEG to compress images. So
it should be at least as good as standard JPEG.

Thanks and Regards
Adi

**Comment by tuqiangwang** [comment]
I just can't guarantee that my input image will produce a heat map of the same size, can I say that? And, as far as you know, there are other GitHub projects that generate heat maps
