### ISSUE TITLE
ROI range size

### ISSUE THREAD

**Issue by tuqiangwang** [iamaaditya/image-compression-cnn#14]
Can I change the heat map range of the output by adjusting the parameters? In other words, making the ROI area wider

**Comment by iamaaditya** [comment]
Unfortunately, no. ROI will be generated of fixed shape.

Thanks and Regards
Adi

**Comment by tuqiangwang** [comment]
I don't think so. I just adjusted the top_k parameter in params to generate different ROI ranges.
