### ISSUE TITLE
Issue with generate_map.py: "TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32"

### ISSUE THREAD

**Issue by subzerofun** [iamaaditya/image-compression-cnn#2]
```
python generate_map.py test.jpg
2017-03-12 06:16:15: I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.8.0.dylib locally
2017-03-12 06:16:15: I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.5.dylib locally
2017-03-12 06:16:15: I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.8.0.dylib locally
2017-03-12 06:16:15: I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.1.dylib locally
2017-03-12 06:16:15: I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.8.0.dylib locally
Traceback (most recent call last):
  File "generate_map.py", line 34, in <module>
    conv_last, gap, class_prob = cnn.build(images_tf)
  File "/Users/ME/github/neural-compression/image-compression-cnn/model.py", line 102, in build
    image = self.image_conversion_scaling(image)
  File "/Users/ME/github/neural-compression/image-compression-cnn/model.py", line 95, in image_conversion_scaling
    r, g, b = tf.split(3, 3, image)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1222, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3426, in _split
    num_split=num_split, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 509, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.
```

I have downloaded the model files and had to change the line 7 from `params.py` to correctly load the `caffe_layers_value.pickle` data.

But for some reason i can't generate the ROI map – is my Tensorflow version (`1.0.1`) too new? You have set the version to `0.11.0` in `requirements.txt`. Do you think the new TF version breaks the code?

**Comment by iamaaditya** [comment]
@subzerofun  Thanks for pointing that out. 

1. It seems Tensorflow updated the split function from `tf.split(axis, num_or_size_splits, value)` to `tf.split(value, num_or_size_splits, axis)`. 

2. Same change in tf.concat `tf.concat(axis, values)` to `tf.concat(values,axis)`.

3. tf.batch_matmul is not tf.matmul 

These changes are in-order to make it work similar to Numpy.

I have pushed the changes. do a pull and it should work fine.

Also, for some reason the models load much slowly in newer version of TF but I have no idea what could be the issue.

**Comment by subzerofun** [comment]
Thanks for the reply! I have just used the official upgrade script from the Tensorflow site, processed all your .py files (no errors after converting) and now everything is running fine!

I just tested a few images and the results are amazing. From what i have read the best JPEG compression algorithm out there is Mozillas [mozjpeg](https://github.com/mozilla/mozjpeg) – comparison:
[Comparison of JPEG Lossless Compression Tools](https://blarg.co.uk/blog/comparison-of-jpeg-lossless-compression-tools)

I will try to process the images from the blog article above and the compare the results. The only problem is that the images are quite big (3000-4000px) and i don't have enough GPU memory at the moment (50+ Chrome tabs...). So the `generate_map.py` script just crashes with an `ResourceExhaustedError` error. Is there any way to reduce the memory usage?

And your algorithm can even reduce a moz-jpeg! Just a short result:
800 x 1000px  ...  _moz-jpeg_ (quality 80/100) ...  **172kb**
... and after cnn compression: **62kb** (!!!)

Of course you can see more artifacts (best visible in smooth regions) compared to the original file. And for some reason the cnn-image is sharper than the original.

Still – overall the ability to reduce the filesize of images, generated with the best jpeg algorithm out there, is amazing!

This is really a great solution for web images! The only downside is the computation time/effort.

**Comment by iamaaditya** [comment]
Thanks for the research. I am glad to hear that it is doing great on moz-jpeg. 

1.  Regardless of the size of the original image, the map being generated used the downsized image of 224x224. See this https://github.com/iamaaditya/image-compression-cnn/blob/master/util.py#L24
(This is because the TF model to generate the heatmaps are trained for specific input dimensions).

2. If you give me what exact error you are getting I might be able to help.

3. I just did  for an image with 5391x4048 pixels and it performed without problem.

4. Computation time is an issue, and we do understand that this makes it not feasible for quick deployment. However, encoding is a one time cost and decoding is as cheap/fast as JPEG. Also, since generating map is GPU based, it can take many images at a time (around 50 for my GPU) and generate the map at the same time.

If you looking to deploy this for an efficient system, get in touch with me. I can help you with that.

**Comment by subzerofun** [comment]
Was trying a 2400 x 3000px image – but only with 1.6 of 6 GB VRAM available. For some reason it worked when i tried running it a second time.

The [3072 x 2304px image from the comparison site](https://c1.staticflickr.com/8/7168/6613482555_c728b627bc_o.jpg) also worked now.
mozjpeg result: from 1,2 MB to 363 kb
CNN result: 305 kb
from compressed mozjpeg to CNN: 335 kb

Thanks for the deployment offer but i'm just testing this for fun :-). Maybe i'll use it for my next website, but since i only write small wordpress themes/sites, i will just need to convert ~50-200 images. That's manageable with a .sh script.

**Comment by iamaaditya** [comment]
Sure. I am glad it works. All the best with your work.
