### ISSUE TITLE
faild when python generate_map.py image.png

### ISSUE THREAD

**Issue by JingjingZhangAndPan** [iamaaditya/image-compression-cnn#3]
python generate_map.py image.png
/usr/local/lib/python2.7/dist-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
Traceback (most recent call last):
  File "generate_map.py", line 32, in <module>
    cnn.load_vgg_weights()
  File "/home/linux/work/tensorflow/image-compression-cnn/model.py", line 33, in load_vgg_weights
    with open(hyper.vgg_weights) as f:
IOError: [Errno 2] No such file or directory: './data/caffe_layers_value.pickle'

is it need to caffe also?
mine tensorflow's version is tensorflow-1.1.0-cp27-cp27mu-manylinux1_x86_64.whl

thanks.

**Comment by JingjingZhangAndPan** [comment]
where could download caffe_layers_value.pickle file?

**Comment by iamaaditya** [comment]
No it does not need Caffe, that was just the name of the CNN weights. They can be downloaded from here
https://drive.google.com/file/d/0B5o40yxdA9PqOVI5dF9tN3NUc2c/view?usp=sharing

**Comment by panyongfeng** [comment]
the link is broken, can you share it again, thanks.
