### ISSUE TITLE
some questions of training 

### ISSUE THREAD

**Issue by JingjingZhangAndPan** [iamaaditya/image-compression-cnn#4]
Hello, would you like help me with below questions?

1. when try to training mime own model,
there has an error occured:
python prepare_data.py
  File "prepare_data.py", line 14
    label_dict             = pd.Series(labels, index = label_names) label_dict - = 1
                                                                             ^
SyntaxError: invalid syntax
is there has any error in the latest codes of master?

2.  before traning mime own model,
is there has any data should be prepared?
    a.  you will need class labelled training examples, like CIFAR, Caltech or Imagenet
		should i install the CIFAR, Caltech or Imagenet in pc?
	b.   what type image could be training? is there has size, content, format limition?
	c.  is there has any place to download those images?	
thanks

**Comment by iamaaditya** [comment]
Hi @JingjingZhangAndPan 

1. I have pushed the change to fix this. Thanks for noticing. I think while formatting the code the line got deleted. You can either put `label_dict - = 1` in a new line or just make it like this
`label_dict = pd.Series(labels, index = label_names) - 1`

2. You need class labelled data. It can be Caltech, ImageNet or CIFAR. The code just expects the files to be organized by class names (one directory per class and the name of the directory should be like this ClassNumber.ClassName
See this for e.g http://gpgpu.cs-i.brandeis.edu/zzz/data/caltech/256_ObjectCategories/
However, this is not important. You can modify prepare.py to suit however you have the data. Just make sure that data is in a Pandas Dataframe with three things
'image_path' (path of the images)
'label' (label number)
'label_name' (name of the class) // although this is not critical and you can just comment out the parts that uses the label_name. Same three things for a dataframe for test images.

**Comment by JingjingZhangAndPan** [comment]
hi, Iammaaditya
is there has method to download the contents in http://gpgpu.cs-i.brandeis.edu/zzz/data/caltech/
such as test.pickle, train.pickle and 256_ObjectCategories
BTW, how to generate the *.pickle file?

**Comment by JingjingZhangAndPan** [comment]
BTW, how to generate the *.pickle file after get ImageNet data set?

**Comment by JingjingZhangAndPan** [comment]
is any method to download 256_ObjectCategories folder?

**Comment by iamaaditya** [comment]
http://www.vision.caltech.edu/Image_Datasets/Caltech256/

Thanks and Regards
Adi

**Comment by JingjingZhangAndPan** [comment]
Hello, Adi
I got below error when run train.py
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
WARNING:tensorflow:From train.py:66: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
/usr/local/lib/python2.7/dist-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
linux@linux-HP-Compaq-Pr

**Comment by JingjingZhangAndPan** [comment]
Hello Adi,
when I run prepare_data.py and train.py, I meet several errors, and I modify some place in codes:
1. prepare_data.py
    a. TrainingParams can't be found
      fixed:
         import params
          tparam = params.TrainingParams(verbose=False)
  2. train.py
     ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
    fixed:
      loss_tf   = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(logits=prob_tf, labels=labels_tf))  in train.py 37 line

after all issue fixed, I also meet an problem:

W tensorflow/core/common_runtime/bfc_allocator.cc:274] **************x**********************************************************************************xxx
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 196.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[32,112,112,128]
Traceback (most recent call last):
  File "train.py", line 87, in <module>
    _, batch_loss, loss_sw = sess.run([train_op, loss_tf, train_loss], feed_dict={images_tf: train_images, labels_tf: train_labels})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,112,112,128]
         [[Node: conv2_2/conv2_2 = Relu[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](conv2_2/dropout/mul)]]
         [[Node: Mean_1/_25 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1951_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'conv2_2/conv2_2', defined at:
  File "train.py", line 35, in <module>
    _,_,prob_tf   = cnn.build(images_tf)
  File "/home/pj_share/zjj/image-compression-cnn/model.py", line 110, in build
    conv2_2    = self.conv2d_depth_or_not(conv2_1, "conv2_2", nonlinearity=tf.nn.relu)
  File "/home/pj_share/zjj/image-compression-cnn/model.py", line 74, in conv2d_depth_or_not
    return nonlinearity(bias, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 2150, in relu
    result = _op_def_lib.apply_op("Relu", features=features, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[32,112,112,128]
         [[Node: conv2_2/conv2_2 = Relu[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](conv2_2/dropout/mul)]]
         [[Node: Mean_1/_25 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1951_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

would you help me to check where has gone error?

thanks

**Comment by JingjingZhangAndPan** [comment]
pj_share@linux-860-089cn:~/zjj/image-compression-cnn$ python2.7 train.py
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
{'batch_size': 32,
 'change_lr_env': False,
 'data_test_path': './data/test.pickle',
 'data_train_path': './data/train.pickle',
 'images_path': './data/images/256_ObjectCategories',
 'learning_rate': 0.002,
 'max_iters': 200000,
 'model_path': './models/',
 'momentum': 0.9,
 'num_epochs': 200,
 'on_resume_fix_lr': False,
 'optimizer': 'Adam',
 'resume_training': False,
 'test_every_iter': 200,
 'weight_decay_rate': 0.0005}
{'cnn_struct': 'vgg',
 'filter_h': 3,
 'filter_w': 3,
 'fine_tuning': True,
 'image_c': 3,
 'image_h': 224,
 'image_w': 224,
 'model_path': 'models/model-50',
 'n_labels': 257,
 'sparse': True,
 'stddev': 0.2,
 'top_k': 5,
 'vgg_weights': '/home/pj_share/zjj/image-compression-cnn/caffe_layers_value.pickle'}
{'conv_filters': [64,
                  64,
                  128,
                  128,
                  256,
                  256,
                  256,
                  512,
                  512,
                  512,
                  512,
                  512,
                  512],
 'depth_filters': [32],
 'last_features': 1024,
 'layer_shapes': {'GAP/W': (1024, 257),
                  'conv1_1/W': (3, 3, 3, 64),
                  'conv1_1/b': (64,),
                  'conv1_2/W': (3, 3, 64, 64),
                  'conv1_2/b': (64,),
                  'conv2_1/W': (3, 3, 64, 128),
                  'conv2_1/b': (128,),
                  'conv2_2/W': (3, 3, 128, 128),
                  'conv2_2/b': (128,),
                  'conv3_1/W': (3, 3, 128, 256),
                  'conv3_1/b': (256,),
                  'conv3_2/W': (3, 3, 256, 256),
                  'conv3_2/b': (256,),
                  'conv3_3/W': (3, 3, 256, 256),
                  'conv3_3/b': (256,),
                  'conv4_1/W': (3, 3, 256, 512),
                  'conv4_1/b': (512,),
                  'conv4_2/W': (3, 3, 512, 512),
                  'conv4_2/b': (512,),
                  'conv4_3/W': (3, 3, 512, 512),
                  'conv4_3/b': (512,),
                  'conv5_1/W': (3, 3, 512, 512),
                  'conv5_1/b': (512,),
                  'conv5_2/W': (3, 3, 512, 512),
                  'conv5_2/b': (512,),
                  'conv5_3/W': (3, 3, 512, 512),
                  'conv5_3/b': (512,),
                  'conv6/W': (3, 3, 1024, 1024),
                  'conv6/b': (1024,),
                  'conv6_1/W': (3, 3, 512, 32),
                  'conv6_1/b': (32,),
                  'depth/W': (3, 3, 32, 32),
                  'depth/b': (1024,)},
 'pool_stride': [1, 2, 2, 1],
 'pool_window': [1, 2, 2, 1]}

W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties:
name: GeForce GTX 980 Ti
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:01:00.0
Total memory: 5.93GiB
Free memory: 5.68GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:01:00.0)
WARNING:tensorflow:From train.py:66: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
/usr/local/lib/python2.7/dist-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 3.45GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 3.02GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 1.27GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 1.72GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (256):       Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (512):       Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (1024):      Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (2048):      Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (4096):      Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (8192):      Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (16384):     Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (32768):     Total Chunks: 1, Chunks in use: 0 32.8KiB allocated for chunks. 6.8KiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (65536):     Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (131072):    Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (262144):    Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (524288):    Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (1048576):   Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (2097152):   Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (4194304):   Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (8388608):   Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (16777216):  Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (33554432):  Total Chunks: 1, Chunks in use: 0 35.96MiB allocated for chunks. 576.0KiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (67108864):  Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (134217728):         Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (268435456):         Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:660] Bin for 196.00MiB was 128.00MiB, Chunk State:
I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709840000 of size 1280
I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709840500 of size 6912
I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709842000 of size 256

**Comment by JingjingZhangAndPan** [comment]
2. Adi
train.py
 ValueError: Only call  sparse_softmax_cross_entropy_with_logits  with named arguments (labels=..., logits=..., ...)
 I modify this error as below:
 loss_tf = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(logits=prob_tf, labels=labels_tf)) 
is it right?

**Comment by iamaaditya** [comment]
Yes, the new TF requires named arguments for softmax.
